export const JOBS_BASE_URL = "https://www.themuse.com/api/public";

export const CATEGORIES = [
  "All category",
  "Accounting",
  "Account Management/Customer Success",
  " Corporate",
  "Customer Service Career",
  "Data Science",
  "Design",
  "Editor",
  "Education",
  "HR",
  "IT",
  "Law",
  "Marketing",
  "Mechanic",
  "Mental Health",
  "Nurses",
  "Office Administration",
  "Physical Assistant",
  "Product",
  "Project Management",
  "Public Relations",
  "Recruiting",
  "Retail",
  "Sales",
  "Software Engineer",
  "UX",
  "Videography",
  "Writer",
];

export const LEVEL = [
  "All level",
  "Entry Level",
  "Mid Level",
  "Senior Level",
  "Management",
  "Internship",
];
